[context.production.environment]
  FIREBASE_API_KEY = "AIzaSyDdGLMo8SACp-7E2g_HXaPs-0VWjBktRpA"
  FIREBASE_AUTH_DOMAIN = "sojourer-web.firebaseapp.com"
  FIREBASE_DATABASE_URL = "https://sojourer-web.firebaseio.com"
  FIREBASE_PROJECT_ID = "sojourer-web"
  FIREBASE_STORAGE_BUCKET = "sojourer-web.appspot.com"
  FIREBASE_MESSAGING_SENDER_ID = "618264640987"

[[headers]]
  for = "/service-worker.js"
  [headers.values]
    cache-control = '''
      max-age=0,
      no-cache,
      no-store,
      must-revalidate'''

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
